#ifndef CORE_CONFIG_H
#define CORE_CONFIG_H

#define DEBUG

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 800
#define TARGET_FPS 60

#define MAX_PLAYER_PROJECTILES 1024
#define MAX_ENEMY_PROJECTILES 1024
#define MAX_XP_BOXES 1024

#define DEFAULT_XP_LIFETIME 5

#endif